-- Создание схемы DM и таблиц

CREATE SCHEMA IF NOT EXISTS "DM";

CREATE TABLE IF NOT EXISTS "DM"."DM_ACCOUNT_TURNOVER_F" (
    "ON_DATE" DATE,
    "ACCOUNT_RK" INTEGER,
    "CREDIT_AMOUNT" NUMERIC(23, 8),
    "CREDIT_AMOUNT_RUB" NUMERIC(23, 8),
    "DEBET_AMOUNT" NUMERIC(23, 8),
    "DEBET_AMOUNT_RUB" NUMERIC(23, 8)
);

CREATE TABLE IF NOT EXISTS "DM"."DM_F101_ROUND_F" (
    "FROM_DATE" DATE,
    "TO_DATE" DATE,
    "CHAPTER" CHAR(1),
    "LEDGER_ACCOUNT" CHAR(5),
    "CHARACTERISTIC" CHAR(1),
    "BALANCE_IN_RUB" NUMERIC(23,8),
    "R_BALANCE_IN_RUB" NUMERIC(23,8),
    "BALANCE_IN_VAL" NUMERIC(23,8),
    "R_BALANCE_IN_VAL" NUMERIC(23,8),
    "BALANCE_IN_TOTAL" NUMERIC(23,8),
    "R_BALANCE_IN_TOTAL" NUMERIC(23,8),
    "TURN_DEB_RUB" NUMERIC(23,8),
    "R_TURN_DEB_RUB" NUMERIC(23,8),
    "TURN_DEB_VAL" NUMERIC(23,8),
    "R_TURN_DEB_VAL" NUMERIC(23,8),
    "TURN_DEB_TOTAL" NUMERIC(23,8),
    "R_TURN_DEB_TOTAL" NUMERIC(23,8),
    "TURN_CRE_RUB" NUMERIC(23,8),
    "R_TURN_CRE_RUB" NUMERIC(23,8),
    "TURN_CRE_VAL" NUMERIC(23,8),
    "R_TURN_CRE_VAL" NUMERIC(23,8),
    "TURN_CRE_TOTAL" NUMERIC(23,8),
    "R_TURN_CRE_TOTAL" NUMERIC(23,8),
    "BALANCE_OUT_RUB" NUMERIC(23,8),
    "R_BALANCE_OUT_RUB" NUMERIC(23,8),
    "BALANCE_OUT_VAL" NUMERIC(23,8),
    "R_BALANCE_OUT_VAL" NUMERIC(23,8),
    "BALANCE_OUT_TOTAL" NUMERIC(23,8),
    "R_BALANCE_OUT_TOTAL" NUMERIC(23,8)
);